// AUTO-GENERATED by scripts/generate-assignments.js
// Do not edit by hand — modify src/assets/assignments/<folder>/meta.json instead.

import { Assignment } from '../models/assignment.model';

export const ASSIGNMENTS: Assignment[] = [
  {
    id: "assignment-01",
    title: "CSS Flexbox Layout",
    description: "A responsive page layout built entirely with CSS Flexbox — navigation bar, hero section, and a card grid.",
    week: 1,
    tags: ["HTML","CSS","Flexbox"],
    previewUrl: "assets/assignments/assignment-01/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/assignment-01/index.html" },
      { name: "style.css", url: "assets/assignments/assignment-01/style.css" },
    ],
    color: "#f093fb, #f5576c",
    category: "route-assignments",
  },
  {
    id: "assignment-02",
    title: "JavaScript Todo App",
    description: "A fully interactive to-do list with add, complete, and delete functionality using vanilla JavaScript and DOM manipulation.",
    week: 2,
    tags: ["HTML","CSS","JavaScript"],
    previewUrl: "assets/assignments/assignment-02/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/assignment-02/index.html" },
      { name: "style.css", url: "assets/assignments/assignment-02/style.css" },
    ],
    color: "#4facfe, #00f2fe",
    category: "route-assignments",
  },
  {
    id: "assignment-03",
    title: "Assignment 03",
    description: "",
    week: 3,
    tags: ["HTML","CSS"],
    previewUrl: "assets/assignments/assignment-03/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/assignment-03/index.html" },
      { name: "style.css", url: "assets/assignments/assignment-03/style.css" },
    ],
    color: "#43e97b, #38f9d7",
    category: "route-assignments",
  },
  {
    id: "assignment-04",
    title: "Assignment 04",
    description: "",
    week: 4,
    tags: ["HTML"],
    previewUrl: "assets/assignments/assignment-04/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/assignment-04/index.html" },
    ],
    color: "#fa709a, #fee140",
    category: "route-assignments",
  },
  {
    id: "assignment-05",
    title: "Assignment 05",
    description: "",
    week: 5,
    tags: ["HTML"],
    previewUrl: "assets/assignments/assignment-05/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/assignment-05/index.html" },
    ],
    color: "#a18cd1, #fbc2eb",
    category: "route-assignments",
  },
];
