// AUTO-GENERATED by scripts/generate-assignments.js
// Do not edit by hand — modify src/assets/assignments/<folder>/meta.json instead.

import { Assignment } from '../models/assignment.model';

export const ASSIGNMENTS: Assignment[] = [
  {
    id: "FitCoreGymLanding",
    title: "FitCoreGymLanding",
    description: "",
    tags: ["HTML"],
    previewUrl: "assets/ALL/landing-pages/FitCoreGymLanding/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/ALL/landing-pages/FitCoreGymLanding/index.html" },
      { name: "style.css", url: "assets/ALL/landing-pages/FitCoreGymLanding/style.css" },
    ],
    color: "#f093fb, #f5576c",
    category: "route-assignments",
  },
  {
    id: "Hoodizz",
    title: "Hoodizz",
    description: "",
    tags: ["HTML"],
    previewUrl: "assets/ALL/landing-pages/Hoodizz/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/ALL/landing-pages/Hoodizz/index.html" },
      { name: "styles.css", url: "assets/ALL/landing-pages/Hoodizz/styles.css" },
    ],
    color: "#4facfe, #00f2fe",
    category: "route-assignments",
  },
  {
    id: "Mudabbir",
    title: "Mudabbir",
    description: "",
    tags: ["HTML"],
    previewUrl: "assets/ALL/landing-pages/Mudabbir/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/ALL/landing-pages/Mudabbir/index.html" },
      { name: "style.css", url: "assets/ALL/landing-pages/Mudabbir/style.css" },
    ],
    color: "#43e97b, #38f9d7",
    category: "route-assignments",
  },
  {
    id: "TheDJIMavic4",
    title: "TheDJIMavic4",
    description: "",
    tags: ["HTML"],
    previewUrl: "assets/ALL/landing-pages/TheDJIMavic4/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/ALL/landing-pages/TheDJIMavic4/index.html" },
      { name: "style.css", url: "assets/ALL/landing-pages/TheDJIMavic4/style.css" },
    ],
    color: "#fa709a, #fee140",
    category: "route-assignments",
  },
  {
    id: "TheUXReview-blogLanding",
    title: "TheUXReview BlogLanding",
    description: "",
    tags: ["HTML"],
    previewUrl: "assets/ALL/landing-pages/TheUXReview-blogLanding/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/ALL/landing-pages/TheUXReview-blogLanding/index.html" },
      { name: "styles.css", url: "assets/ALL/landing-pages/TheUXReview-blogLanding/styles.css" },
    ],
    color: "#a18cd1, #fbc2eb",
    category: "route-assignments",
  },
];
