// AUTO-GENERATED by scripts/generate-assignments.js
// Do not edit by hand — modify src/assets/assignments/<folder>/meta.json instead.

import { Assignment } from '../models/assignment.model';

export const ASSIGNMENTS: Assignment[] = [
  {
    id: "FitCoreGymLanding",
    title: "JavaScript Todo App",
    description: "A fully interactive to-do list with add, complete, and delete functionality using vanilla JavaScript and DOM manipulation.",
    week: 2,
    tags: ["HTML","CSS","JavaScript"],
    previewUrl: "assets/assignments/FitCoreGymLanding/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/FitCoreGymLanding/index.html" },
      { name: "style.css", url: "assets/assignments/FitCoreGymLanding/style.css" },
    ],
    color: "#4facfe, #00f2fe",
    category: "route-assignments",
  },
  {
    id: "TheDJIMavic4",
    title: "Assignment 03",
    description: "",
    week: 3,
    tags: ["HTML","CSS"],
    previewUrl: "assets/assignments/TheDJIMavic4/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/TheDJIMavic4/index.html" },
      { name: "style.css", url: "assets/assignments/TheDJIMavic4/style.css" },
    ],
    color: "#43e97b, #38f9d7",
    category: "route-assignments",
  },
  {
    id: "TheUXReview-blogLanding",
    title: "TheUXReview BlogLanding",
    description: "",
    tags: ["HTML"],
    previewUrl: "assets/assignments/TheUXReview-blogLanding/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/TheUXReview-blogLanding/index.html" },
    ],
    color: "#43e97b, #38f9d7",
    category: "route-assignments",
  },
  {
    id: "assignment-05",
    title: "Assignment 05",
    description: "",
    week: 5,
    tags: ["HTML"],
    previewUrl: "assets/assignments/assignment-05/index.html",
    downloadFiles: [
      { name: "index.html", url: "assets/assignments/assignment-05/index.html" },
      { name: "style.css", url: "assets/assignments/assignment-05/style.css" },
    ],
    color: "#fa709a, #fee140",
    category: "route-assignments",
  },
];
